baseURL = "https://richardhcli.github.io/"
locale = "en-us"
title = "Richard Li"
publishDir = "build"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Richard Li. Machine learning architecture."
  role = "ML Engineer · Firmware Tinkerer · EE Builder"
  location = "West Lafayette, Indiana"
  email = "richardhcli@gmail.com"
  github = "https://github.com/richardhcli"
  linkedin = "https://www.linkedin.com/in/richardhcli"
  resume = "https://drive.google.com/file/d/1nKXqQy7LzwMQU_mMiYjSvF6az85v4pTR/view?usp=drive_link"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"
    noClasses = true

[permalinks]
  blog = "/blog/:slug/"
  projects = "/projects/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
