baseURL = "https://richardhcli.github.io/"
locale = "en-us"
title = "Richard Li"
publishDir = "build"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Machine learning architecture Enthusiast"
  role = "EE + CS B.S."
  location = "West Lafayette, Indiana"
  email = "richardhcli@gmail.com"
  github = "https://github.com/richardhcli"
  linkedin = "https://www.linkedin.com/in/richardhcli"
  resume = "/resume/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"
    noClasses = true

[[permalinks]]
  pattern = "/resume/"
  [permalinks.target]
    kind = "page"
    path = "/resume"

[[permalinks]]
  pattern = "/blog/:slug/"
  [permalinks.target]
    kind = "page"
    path = "/blog/**"

[[permalinks]]
  pattern = "/projects/:slug/"
  [permalinks.target]
    kind = "page"
    path = "/projects/**"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
