baseURL = "https://richardhcli.github.io/"
locale = "en-us"
title = "Richard Li"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Richard Li. Machine learning architecture."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"
    noClasses = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
